name: Actualización de datos

on:
  schedule:
    - cron: '0,30 * * * *' 
  workflow_dispatch:  # Para ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # <-- OTORGAR PERMISOS DE ESCRITURA AL CONTENIDO DEL REPO

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run Python script
        run: |
          python main.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add df_enriched.csv
          git add df_atipicos.csv
          git commit -m "Update CSV (cron job) [skip ci]" || echo "No changes to commit"
          git push
